### ISSUE TITLE
Getting Error When Running shortcuts.py

### ISSUE THREAD

**Issue by Teutonic84** [CorporalQuesadilla/Steam-Shortcut-Manager#1]
I'm trying to test out the python script and i'm getting some errors. I'm running python 2.7 currently.

> "C:\Users\USER\Downloads\Steam-Shortcut-Manager-master\shortcuts.py"
>  "C:\Program Files (x86)\Steam\userdata\19087720\config\shortcuts.vdf" "TEST Balloon Fight" "C:\SteamConsole\Scripts\Launcher.bat" C:\ "" "" "" 0 1 1 1 0 Test FPS
> Traceback (most recent call last):
>   File "C:\Users\USER\Downloads\Steam-Shortcut-Manager-master\shortcuts.py", line 241, in <module>
>     main()
>   File "C:\Users\USER\Downloads\Steam-Shortcut-Manager-master\shortcuts.py", line 236, in main
>     lastEntryInfo = findLastEntryNumberAndPosition(pathToShortcutsVDF)
>   File "C:\Users\USER\Downloads\Steam-Shortcut-Manager-master\shortcuts.py", line 111, in findLastEntryNumberAndPosition
>     return (lastEntryNumber, lastEntryPosition)
> UnboundLocalError: local variable 'lastEntryPosition' referenced before assignment

**Comment by seanocali** [comment]
Same error here.

`C:\Users\***\Desktop\Steam-Shortcut-Manager-master>python shortcuts.py "C:\Program Files (x86)\Steam\userdata\*******\config\shortcuts.vdf" "NPD" "C:\notepad++.exe" C:\ "C:\NPD" "" "-s" 0 1 1 1 0 Arcade Desktop
Traceback (most recent call last):
  File "shortcuts.py", line 241, in <module>
    main()
  File "shortcuts.py", line 236, in main
    lastEntryInfo = findLastEntryNumberAndPosition(pathToShortcutsVDF)
  File "shortcuts.py", line 111, in findLastEntryNumberAndPosition
    return (lastEntryNumber, lastEntryPosition)
UnboundLocalError: local variable 'lastEntryPosition' referenced before assignment`

**Comment by seanocali** [comment]
I added a declaration of lastEntryPosition and that error went away, I then got this error instead:
```
C:\Users\*****\Desktop\Steam-Shortcut-Manager-master>python shortcuts.py "C:\Program Files (x86)\Steam\userdata\*****\config\shortcuts.vdf" "NPD" "C:\notepad++.exe" C:\ "C:\NPD" "" "-s" 0 1 1 1 0 Arcade Desktop
Traceback (most recent call last):
  File "shortcuts.py", line 242, in <module>
    main()
  File "shortcuts.py", line 238, in main
    inputTuple = inputPreperation(sys.argv, lastEntryInfo)
  File "shortcuts.py", line 174, in inputPreperation
    var_entryID = str(int(lastEntryInfo[0])+1)
ValueError: invalid literal for int() with base 10: ''
```

**Comment by Teutonic84** [comment]
I think we got trolled. This guy seems to have disappeared after getting our hopes up. :(

**Comment by andrewleosteel** [comment]
Replacing line 81 in `shortcuts.py`:
```
    lastEntryNumber = ''
```
with:
```
    lastEntryNumber = 0
    lastEntryPosition = 0
```

Fixed the remaining errors for me, and I was able to successfully add a shortcut using the script after.
